### ISSUE TITLE
Feature request: Make facet_wrap_paginate facet sizes match on last page

### ISSUE THREAD

**Issue by billdenney** [thomasp85/ggforce#132]
First, thanks for the new release!

This is slightly related to #67.

Is there a way to make the last page of a `facet_*_paginate()` plot have facets the same size as the prior pages?  (My looking suggests not or at least not automatically.)  I'd like to request it as a feature, please.

``` r
library(tidyverse)
#> Warning: package 'tibble' was built under R version 3.5.2
#> Warning: package 'readr' was built under R version 3.5.2
#> Warning: package 'dplyr' was built under R version 3.5.2
library(ggforce)
ggplot(diamonds) +
  geom_point(aes(carat, price), alpha = 0.1) +
  facet_wrap_paginate(~ cut:clarity, ncol = 3, nrow = 3, page = 4)
```

![](https://i.imgur.com/9bt0Qie.png)

``` r
ggplot(diamonds) +
  geom_point(aes(carat, price), alpha = 0.1) +
  facet_wrap_paginate(~ cut:clarity, ncol = 3, nrow = 3, page = 5)
```

![](https://i.imgur.com/1Dv7Kij.png)

Created on 2019-03-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by pooranis** [comment]
You would need to _a priori_ know the size of the panels (or the page size from which to calculate the panel size).  Panels in ggplot2 have "null" units - they expand to fill the size of the plot device.  That's why the last page has taller panels - because there are fewer rows.  If you knew explicitly how big you wanted each panel to be, you could set their widths and heights using some absolute unit (inches, cm, whatever).

Currently, you can use the egg package to do this.  See their vignette: https://cran.r-project.org/web/packages/egg/vignettes/Overview.html#setting-panel-size

**Comment by billdenney** [comment]
I was thinking that with this, the panels on the last page would not longer fill the plot device area.  Then, since the number of rows and columns are known the panels could be placed such that they were the same size.  Perhaps one or more empty rows of panels could be inserted (I don't know if this is possible with ggplot)?

**Comment by thomasp85** [comment]
This should be fixed
