### ISSUE TITLE
annotation polygon clipped off at plot edge

### ISSUE THREAD

**Issue by royfrancis** [thomasp85/ggforce#169]
Here is an example:

```
ggplot(data=iris,aes(Petal.Length,Petal.Width,colour=Species))+
  geom_point()+
  geom_mark_ellipse()
```

![index](https://user-images.githubusercontent.com/5083500/64556124-1d54ae00-d33f-11e9-83d1-7f973ab4179d.png)

The annotation polygon gets clipped off. Is there an argument/setting to include the polygon completely rather than having to manually adjusting the axes limits?

**Comment by thomasp85** [comment]
There is not as the expansion of the polygon is calculated at draw time because it uses absolute units (eg. 1 cm), while expansion is calculated during build and is relative. If you resize the plot you'll see that eventually the polygons will be fully shown as the scale expansion increases beyond the polygon expansion
