### ISSUE TITLE
`facet_wrap_paginate()` fails with dir = "v"

### ISSUE THREAD

**Issue by mikmart** [thomasp85/ggforce#179]
I’m trying to paginate a `facet_wrap()` plot with `dir = "v"`, such as this:

``` r
library(ggplot2)
library(ggforce)

d <- data.frame(g = rep(1:6, 5), x = runif(6 * 5), y = rnorm(6 * 5))

p <- ggplot(d, aes(x, y)) + geom_point()
p + facet_wrap(vars(g), dir = "v", ncol = 3)
```

![](https://i.imgur.com/NayAIca.png)

Translating this to paginate by row with `facet_wrap_paginate()`, the results are strange. Page 1 gives a malformed result, and page 2 just errors out:

``` r
p + facet_wrap_paginate(vars(g), dir = "v", ncol = 3, nrow = 1, page = 1)
```

![](https://i.imgur.com/C3b4L00.png)

``` r
p + facet_wrap_paginate(vars(g), dir = "v", ncol = 3, nrow = 1, page = 2)
#> Warning in min(layout$ROW): no non-missing arguments to min; returning Inf
#> Warning in max(layout$COL): no non-missing arguments to max; returning -Inf
#> Warning in max(layout$ROW): no non-missing arguments to max; returning -Inf
#> Warning in matrix(list(zeroGrob()), nrow = nrow, ncol = ncol): NAs
#> introduced by coercion to integer range
#> Error in matrix(list(zeroGrob()), nrow = nrow, ncol = ncol): invalid 'nrow' value (too large or NA)
```

![](https://i.imgur.com/pT26Sp6.png)

Above, I would expect to see two 1x3 plots with panels (1, 3, 5) in the first plot, and panels (2, 4, 6) in the second one.

Swapping to by column does not really seem to improve the situation. Here, I would expect to get three 2x1 plots with panels (1, 2), then (3, 4), and finally (5, 6):

``` r
p + facet_wrap_paginate(vars(g), dir = "v", ncol = 1, nrow = 2, page = 1)
```

![](https://i.imgur.com/3xZbPtz.png)

``` r
p + facet_wrap_paginate(vars(g), dir = "v", ncol = 1, nrow = 2, page = 2)
```

![](https://i.imgur.com/7a6zOd3.png)

``` r
p + facet_wrap_paginate(vars(g), dir = "v", ncol = 1, nrow = 2, page = 3)
#> Warning in min(layout$ROW): no non-missing arguments to min; returning Inf
#> Warning in max(layout$COL): no non-missing arguments to max; returning -Inf
#> Warning in max(layout$ROW): no non-missing arguments to max; returning -Inf
#> Warning in matrix(list(zeroGrob()), nrow = nrow, ncol = ncol): NAs
#> introduced by coercion to integer range
#> Error in matrix(list(zeroGrob()), nrow = nrow, ncol = ncol): invalid 'nrow' value (too large or NA)
```

![](https://i.imgur.com/eaVaD5k.png)

**Comment by danjea-kit** [comment]
I ran into a similar issue multiple times:
`Error in matrix(list(zeroGrob()), nrow = nrow, ncol = ncol) : 
  invalid 'nrow' value (too large or NA)`

my original ggplot2::facet_wrap generated 20 plots. 
I original set nrow = 3 and ncol = 3
I also originally set a number of pages; but it turns out you must use the wrapper ggforce::n_pages()

Then you must run your plot a first time and use the wrapper and create an object with it.
Finally you have to use for loop/sapply/map to generate the graphs per pages.
This finally worked in rmarkdown (also knitting the output) after several attempt.

I also isolated this specific chunk, for whatever reason it was conflicting in the output with a different plot in the same chunk so I split them appart and now the plot + n_pages() + forloop are isolated in a single chunk. 

Check this to help you out with the multiwrapping [https://www.programmingwithr.com/how-to-make-your-facet-wrap-facet-grid-ggplots-span-across-multiple-pages-in-pdf/]

Hope it helps
